# Simly add your estimators as shown below

# Supported types: legacy, ukf
# Supported models: See lsy_models.models.available_models, i.e. fitted_DI_rpyt, mellinger_rpyt

[debug]
timings = true   # print the timings of each estimator
save_data = true # store the raw data and estimates into pickle files

[estimator1]
estimator_type = "ukf"
drone_name = "cf6"
dynamics_model = "fitted_DI_rpy"
estimate_forces_motor = false
estimate_forces_dist = true
estimate_torques_dist = true

# [estimator2]
# estimator_type = "legacy"
# drone_name = "cf90"
# dynamics_model = "fitted_DI_rpy"
# estimate_forces_motor = false
# estimate_forces_dist = false
# estimate_torques_dist = false
