# Simly add your estimators as shown below

# Supported types: legacy, ukf
# Supported models: See lsy_models.models.available_models, i.e. fitted_DI_rpy, mellinger_rpyt

[global] # TODO rename to global
frequency = 240
timings = true    # print the timings of each estimator
save_data = false # store the raw data and estimates into pickle files

# [estimator1]
# estimator_type = "legacy"
# drone_name = "cf6"
# drone_config = "cf2x_L250"
# dynamics_model = "mellinger_rpyt"
# estimate_forces_motor = true
# estimate_forces_dist = true
# estimate_torques_dist = true

# [estimator2]
# estimator_type = "legacy"
# drone_name = "cf99"
# drone_config = "cf2x_L250"
# dynamics_model = "fitted_DI_rpy"
# estimate_forces_motor = false
# estimate_forces_dist = true
# estimate_torques_dist = true

[estimator3]
estimator_type = "legacy"
drone_name = "cf52"
drone_config = "cf2x_L250"
dynamics_model = "fitted_DI_rpy"
estimate_forces_motor = false
estimate_forces_dist = true
estimate_torques_dist = true

# [estimator4]
# estimator_type = "legacy"
# drone_name = "cf52"
# drone_config = "cf2x_L250"
# dynamics_model = "fitted_DI_rpy"
# estimate_forces_motor = false
# estimate_forces_dist = true
# estimate_torques_dist = true
